Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,8 +47,16 @@ jobs:
       - name: Make Repository Files for Sileo
         run: |
           mkdir -p public/debs
-          find . -name "*.deb" -exec cp {} public/debs/ \;
           
+          # Tự động tìm tất cả file .deb ở mọi ngóc ngách và copy vào thư mục public/debs
+          find . -type f -name "*.deb" ! -path "./public/*" -exec cp {} public/debs/ \;
+          
+          # Kiểm tra xem có file deb nào không trước khi quét
+          if [ -z "$(ls -A public/debs)" ]; then
+             echo "Error: Không tìm thấy file .deb nào được tạo!"
+             exit 1
+          fi
+
           cd public
           dpkg-scanpackages -m debs /dev/null > Packages
           bzip2 -9 -c Packages > Packages.bz2
